### ISSUE TITLE
Add some methods for the cell

### ISSUE THREAD

**Issue by JosePizarro3** [FAIRmat-NFDI/nomad-simulations#136]
I am going to add some methods to `ModelSystem` and/or `Cell`/`AtomicCell` to make our lives easier during parsing:

- `from_ase()`: right now we have `to_ase`, but we can define the "from" one.
- `get_atom_symbols()`: this one is to pass the `AtomsState(chemical_symbol)` information to a flat list (as it was originally in the schema).

@ndaelman-hu @EBB2675 please, feel free to suggest other methods that you think might be interesting as well

**Comment by ndaelman-hu** [comment]
okay, thx for the heads-up! maybe some ideas will come when reviewing the draft

> get_atom_symbols(): this one is to pass the AtomsState(chemical_symbol) information to a flat list (as it was originally in the schema).

So you mean that the function returns `list[str]`?

**Comment by JosePizarro3** [comment]
> okay, thx for the heads-up! maybe some ideas will come when reviewing the draft
> 
> > get_atom_symbols(): this one is to pass the AtomsState(chemical_symbol) information to a flat list (as it was originally in the schema).
> 
> So you mean that the function returns `list[str]`?

yeah
