### ISSUE TITLE
add info about symmetrization method + provenance of coordinates

### ISSUE THREAD

**Issue by JFRudzinski** [FAIRmat-NFDI/nomad-simulations#156]
@EBB2675 @ndaelman Can someone provide details?

**Comment by ndaelman-hu** [comment]
I'd need a bit more context to follow you.

**Comment by EBB2675** [comment]
same here

**Comment by JFRudzinski** [comment]
@JosePizarro3 Is this something that you added to clickup? Can you explain?

**Comment by JosePizarro3** [comment]
> @JosePizarro3 Is this something that you added to clickup? Can you explain?

If I add it, the only thing I remember is having a conversation with the magres people at some point as they wanted to see the operations done during symmetrization when the `matID` is applied. 

But I leave the decision to you and Lauri. For me, it is not that important to get this symmetrizing operations in the schema.

**Comment by JFRudzinski** [comment]
Ok, then I will close this for now since Sathya is in contact with Laurie, so it will come up there if necessary, thanks!
