### ISSUE TITLE
Handling of labels in AtomicCell

### ISSUE THREAD

**Issue by JosePizarro3** [FAIRmat-NFDI/nomad-simulations#5]
From the #1 review and after our [meeting on 08.02.2024](https://github.com/FAIRmat-NFDI/AreaC-Meetings/discussions/31), we have to polish the definitions `AtomicCell.labels` and `AtomicCell.atomic_numbers`.

- @ndaelman-hu commented that these quantities should live separately in some section called `AtomType`, possibly merged with the same concepts as in `run.method.atom_parameters`.
- @JFRudzinski commented that we should have 2 quantities to handle generic `labels` and specific `chemical_symbols`, specially to use in the context of models, otherwise it is very buggy when handling normalizations and using ASE.

In my opinion, `AtomicCell` should have a generic `labels`. Then, a couple of classes could be inheriting from it, and then used to be populated in `ModelSystem.atomic_cell`. These two classes (names? `CoarseGrainedCell`, `ElementsCell`?), will then overwrite the meaning of `labels`. Any other extra class (e.g., `LatticeModel`) could be used to overwrite again `labels`. 

I guess that if `labels` exist under some other class `AtomType`, then we can have multiple inheritance in our classes, but I am not 100% sure.

Let's discuss a bit, and I will tackle the issue.

**Comment by JFRudzinski** [comment]
I am pretty open to whatever solution you think is best. After patching the issue and thinking about it some more, I think the more important thing, beyond the particular quantities, naming, etc, is that the normalization pipeline consistently deals with the different cases. This is no easy task currently, so we will just have to keep an eye on it as we implement the new schema and corresponding normalization.

**Comment by JosePizarro3** [comment]
> I am pretty open to whatever solution you think is best. After patching the issue and thinking about it some more, I think the more important thing, beyond the particular quantities, naming, etc, is that the normalization pipeline consistently deals with the different cases. This is no easy task currently, so we will just have to keep an eye on it as we implement the new schema and corresponding normalization.

I think the normalization handles pretty well the fact that we have real chemical symbols or atomic numbers. If this is not the case, the normalization will not run. I'll argue that then it is a matter of splitting `AtomicCell` into N classes which inherit from it, and that this normalization should be moved to the corresponding class which handles chemical symbols, but not for models.

**Comment by JosePizarro3** [comment]
@ndaelman-hu do you have some test files with core-holes? I couldn't find any and I am testing some stuff.

**Comment by ndaelman-hu** [comment]
> @ndaelman-hu do you have some test files with core-holes? I couldn't find any and I am testing some stuff.

Look for usage of `get_template_active_orbitals()`. If you migrate the schema, I can afterward add the normalization: it should be solidified a bit more.
