### ISSUE TITLE
Add `ElectronicEigenvalues` and `ElectronicBandStructure` properties

### ISSUE THREAD

**Issue by JosePizarro3** [FAIRmat-NFDI/nomad-simulations#52]
Adding a base class for the `ElectronicEigenvalues(PhysicalProperty)`, `ElectronicBandStructure(PhysicalProperty)` and `FermiSurface(PhysicalProperty)`. These should contain the electronic energies in terms of the k points for different conditions.

@ndaelman-hu question here: do we define a new `Variables` class for the 3d k points, or simply add a `k_mesh_ref`? I would go for the second option, as we do not want to keep things doubly stored, but maybe is a good oportunity to think about the interplay between ModelMethod and Variables?

**Comment by JosePizarro3** [comment]
I forgot: this is connected with #33, as `ElectronicBandStructure` should inherit from this class. At least this is what I had in mind, it is open for discussion.

**Comment by ndaelman-hu** [comment]
> @ndaelman-hu question here: do we define a new `Variables` class for the 3d k points, or simply add a `k_mesh_ref`? I would go for the second option, as we do not want to keep things doubly stored, but maybe is a good oportunity to think about the interplay between ModelMethod and Variables?

I'd also rather go for the 2nd suggestion, yes. Not only to circumvent doubly storing, but also doubly writing the same information.

**Comment by JosePizarro3** [comment]
After our meeting with Alvin: should we define the value as a HDF5Reference for the ElectronicEigenvalues? This might save tons of storage (but I am not thinking we have to store eigenvalues ALL the time)

**Comment by ndaelman-hu** [comment]
> After our meeting with Alvin: should we define the value as a HDF5Reference for the ElectronicEigenvalues? This might save tons of storage (but I am not thinking we have to store eigenvalues ALL the time)

This touches again on _which actor decides the storage mode_: the schema, normalizer, or parser? In case of the former, wouldn't we always be forced to store it as such?

Personally, I think that we should have some automated system that decides at which data size to store in HDF5.
NOMAD should then handle reading/writing to message pack or HDF5 automatically. But for now this is a pipe dream...

So, if we have to make a generic choice via the schema, I'm kind of unsure. I haven't seen any case yet where eigenvalues warrant the heavy storage. I think that electron densities and wavefunctions are more appropriate use case.

We could in principle decide to **write almost all longer arrays to HDF5**, though, retaining mostly small metadata in message pack. My main worries there are:

1. the _HDF5 implementation is quite new_, so we should test it a bit first.
2. _what this would mean for visualization?_ I know that we have these HDF5 plots, but I haven't really worked with them myself.

If these concerns are addressed, I'm fine with doing it like this.

**Comment by JosePizarro3** [comment]
We don't need to visualize anything with the eigenvalues. But we can discuss this later on.

I thought @ladinesa  said before that it was not possible to automatically decide between HDF5 and msgpack, but I might have not listened the full conversation.

**Comment by ladinesa** [comment]
> We don't need to visualize anything with the eigenvalues. But we can discuss this later on.
> 
> I thought @ladinesa said before that it was not possible to automatically decide between HDF5 and msgpack, but I might have not listened the full conversation.

Indeed it is not possible at the moment you have to know a priori if it is intented as HDFDataset

**Comment by ndaelman-hu** [comment]
> it was not possible to automatically decide between HDF5 and msgpack

That's why I called it _a pipe dream_ for the time being... Still, deciding this shouldn't be the task of the schema.

> We don't need to visualize anything with the eigenvalues.

I more so meant that HDF5 could also apply to other electronic structure aspects, e.g. bands, Fermi surface, DOS. Here, visualization would actually be relevant. **But fine, I'd advise against its use here.**

**Comment by JosePizarro3** [comment]
Actually, `eigenvalues` can become a quite big matrix. Fermi surface as well. Bands and DOS are not. 

Thus, for eigenvalues, I would go with `value = Quantity(type=HDF5Reference)`. Furthermore, we need a way of treating contributions within the HDF5 framework, as well as weights / intensities at each k point, but let's discuss somewhere this next week

**Comment by JosePizarro3** [comment]
Just a note I realized now: I will separate `FermiSurface` into its own issue and pull request.
