### ISSUE TITLE
Adding unit testing

### ISSUE THREAD

**Issue by JosePizarro3** [FAIRmat-NFDI/nomad-simulations#9]
Following @ndaelman-hu and Alvin's suggestion, we will add unit testing for the different classes and functions.

We can follow Alvin's implementation in the [test of the simulation workflow schema](https://github.com/nomad-coe/nomad-schema-plugin-simulation-workflow/blob/develop/tests/test_simulationworkflowschema.py).

This will be tackled separately, adding unit testing for:
- [x] `model_system.py`, `atoms_state.py` (#15)
- [x] `model_method.py` (@ndaelman-hu needs to tackle the DFT schema and add testing #13)
- [x] `numerical_settings.py` (to be tackled separately together with the work on `BasisSet`, @ndaelman-hu)
- [x] `general.py`
- [x] `outputs.py`

This testing will probably polish the current functionalities, and perhaps add new ones that are missing.

**Comment by JosePizarro3** [comment]
@ndaelman-hu @ladinesa during the dev of unit testing: should we also add testing for the `normalize()` functions of each class? What if these are empty or just normalize the super level?

**Comment by ladinesa** [comment]
> @ndaelman-hu @ladinesa during the dev of unit testing: should we also add testing for the `normalize()` functions of each class? What if these are empty or just normalize the super level?

not sure if i understood it correctly, but we should set up the test such that the normalize function gets executed. We do not need to create a test for each class, we can also just put the test in the parent class if the normalization is simple enough for a single test function.

**Comment by JosePizarro3** [comment]
> not sure if i understood it correctly,

Ok, let me push something this week, and you tell me whether I got the unit testing idea wrong.

**Comment by JosePizarro3** [comment]
Please @ndaelman-hu check this issue, I left some things opened for you to tackle when you want to implement DFT and BasisSet schemas.

Here, I am satisfied so far with the current coverage.
